name: NIGHTLY
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  Build:
    runs-on: 'ubuntu-latest'
    env:
      VERSION: nightly

    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: xvfb-run npm run all
